language: c
sudo: required
#dist: trusty
before_install:
# Yara
  - wget https://github.com/VirusTotal/yara/archive/v3.6.3.tar.gz -O yara.tar.gz
  - tar -xzvf yara.tar.gz
# R2 module for Yara
  - cp r2.c yara-3.6.3/libyara/modules/r2.c
  - cp dist/yara-3.6.3/libyara/modules/module_list yara-3.6.3/libyara/modules/module_list
  - cp dist/yara-3.6.3/libyara/Makefile.am yara-3.6.3/libyara/Makefile.am
  - cp dist/yara-3.6.3/configure.ac yara-3.6.3/configure.ac
  - echo "AM_CFLAGS += @DOLLAR_SIGN@(shell pkg-config --cflags r_socket)" >> yara-3.6.3/Makefile.am
  - echo "LIBS += @DOLLAR_SIGN@(shell pkg-config --libs r_socket)" >> yara-3.6.3/Makefile.am

# libjansson
  - wget http://www.digip.org/jansson/releases/jansson-2.7.tar.gz
  - tar -xzvf jansson-2.7.tar.gz
  - cd jansson-2.7
  - ./configure
  - make
  - sudo make install
  - cd ..

# Install radare2
  - git clone https://github.com/radare/radare2.git
  - cd radare2 && ./sys/install.sh
  
# Compile Yara
  - cd ../yara-3.6.3
  - ./bootstrap.sh
  - ./configure --enable-cuckoo
  - make
  - sudo make install
  - sudo ldconfig

# Download requirements.txt
#  - sudo pip install -r requirements.txt

script:
  - cd ../
  - ls
  - python launch_tests.py
